# Generated by Django 4.1.7 on 2023-04-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='text_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
